force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Duration__c.field-meta.xml
<CustomField>
    <fullName>Project_Duration__c</fullName>
    <label>Project Duration</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProjectClass.cls
@isTest
public class ProjectClass {
    public @isTest static void main(){
        List<Project__c> projList = new List<Project__c>();// collection
        
        Project__c proj_obj = new Project__c(); //instance
        proj_obj.Name= 'chai';
         proj_obj.Project_Duration__c = '20';
         projList.add(proj_obj);
        insert projList;
        
        
       
      /*  proj_obj.add()
        projList.add('Sony');
        projList.add('Dell');
        projList.add('Lenovo');
        System.debug('Display the ProjectList' + projList);*/
    }

}