force-app/main/default/objects/Retail_Store__c/Retail_Store__c.object-meta.xml
<CustomObject>
    <label>Retail Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Store__c/fields/Days_Since_Opening__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Opening__c</fullName>
    <label>Days Since Opening</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Retail_Store__c/fields/Opening_Date__c.field-meta.xml
<CustomField>
    <fullName>Opening_Date__c</fullName>
    <label>Opening Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RetailStoreDaysSinceOpening.cls
public class RetailStoreDaysSinceOpening {
    
    public static void updateDaysSinceOpening(List<Retail_Store__c> storesToUpdate) {
        for (Retail_Store__c store : storesToUpdate) {
            //Integer daysSinceOpening = store.Opening_Date__c.daysBetween(Date.Today());
            Integer daysSinceOpening = Math.abs(Date.today().daysBetween(store.Opening_Date__c));
            store.Days_Since_Opening__c = daysSinceOpening;
        }
    }
}